name: CI Test

on:
    pull_request:
        branches: [ "master" ]

    push:
        branches: [ "master" ]

jobs:
    matrix:
        name: Unittest Matrix
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                python-version: ["3.7","3.8","3.9"]
                django: [ "1.11", "2.2",]
                exclude:
                    - python-version: "3.8"
                      django: "1.11"
                    
                    - python-version: "3.9"
                      django: "1.11"
                    

        services:
            postgres:
                image: postgres
                # Set health checks to wait until postgres has started
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    # Maps tcp port 5432 on service container to the host
                    - 5432:5432
                env:
                    # Docker image requires a password to be set
                    POSTGRES_PASSWORD: "postgres"

        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-python@v3
                with:
                    python-version: ${{ matrix.python-version }}
            -   run: pip install tox
            -   run: tox -v -- -v
                env:
                    TOXENV: py${{ matrix.python-version }}-django${{ matrix.django }}
